apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-cpu-limit-range
  namespace: {{ .Release.Name }}
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "128Mi"
    defaultRequest:
      cpu: "50m"
      memory: "100Mi"
    type: Container
