apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-default-quota
  namespace: {{ .Release.Name }}
spec:
  hard:
    limits.cpu: {{ .Values.resourceQuota.limitsCpu }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory }}
    services.loadbalancers: 0
    services.nodeports: 0
    services: {{ .Values.resourceQuota.services }}
    replicationcontrollers: 100
    configmaps: 100
